-- Run this file separately in D1 Studio when importing the existing team cards.
-- INSERT OR IGNORE makes it safe to run again without duplicating profiles.
INSERT OR IGNORE INTO team (id, name, role_fr, role_en, bio_fr, bio_en, department, phone, photo_url, published, sort_order, created_at, updated_at)
VALUES
('team-dr-soh', 'Dr. Soh', 'Medecin Generaliste', 'General Practitioner', 'Accompagnement global en medecine generale, avec une specialisation en sante reproductive et perinatale.', 'Comprehensive general practice care with a focus on reproductive and perinatal health.', 'medecine', '+237677609056', '/imgteam1.jpg', 1, 1, datetime('now'), datetime('now')),
('team-negou-liliane', 'Dr. Negou Liliane', 'Medecin Generaliste', 'General Practitioner', 'Suivi des adultes et consultations de garde en soiree.', 'Adult follow-up care and evening on-call consultations.', 'medecine', '+237650128282', '/pathologies/imgteam2.jpg', 1, 2, datetime('now'), datetime('now')),
('team-flaure-tchopda', 'Dr Flaure Tchopda Epse Kamdoum', 'Biologiste Medicale', 'Medical Biologist', 'Analyses de routine et remise des resultats sous 24h.', 'Routine analyses with results delivered within 24 hours.', 'labo', '+237697791411', '/pathologies/imgteam3.jpg', 1, 3, datetime('now'), datetime('now')),
('team-tene-soh', 'Dr Tene Soh Dylan Parfait', 'Medecin Generaliste', 'General Practitioner', 'Suivi des adultes et consultations de garde en soiree.', 'Adult follow-up care and evening on-call consultations.', 'medecine', '+237677609056', '/pathologies/imgteam4.png', 1, 4, datetime('now'), datetime('now')),
('team-hameni-romario', 'Hameni Romario', 'Sage-femme', 'Midwife', 'Accompagnement obstetrical complet et suivi prenatal pour les patientes et leurs familles.', 'Complete obstetric support and prenatal follow-up for patients and their families.', 'medecine', '+237696641068', '/pathologies/imgteam5.png', 1, 5, datetime('now'), datetime('now')),
('team-fotso-valerie', 'Mme Fotso Valerie', 'Preparatrice en Pharmacie', 'Pharmacy Assistant', 'Coordination des preparations pharmaceutiques et suivi des stocks essentiels.', 'Coordinates pharmaceutical preparation and manages essential stock levels.', 'pharmacie', '+237699157869', '/pathologies/imgteam6.png', 1, 6, datetime('now'), datetime('now')),
('team-samen-ornella', 'Samen Ornella', 'Technicienne de Laboratoire', 'Lab Technician', 'Assure le lien entre le laboratoire et la pharmacie pour la preparation des traitements.', 'Bridges the laboratory and pharmacy for treatment preparation.', 'pharmacie', '+237674299039', '/pathologies/imgteam7.png', 1, 7, datetime('now'), datetime('now')),
('team-tchassi-danielle', 'Tchassi Tsinkou Danielle', 'Technicien de Laboratoire', 'Lab Technician', 'Specialiste des prelevements biologiques et du support technique en pharmacie principale.', 'Specializes in biological sampling and technical support for the main pharmacy.', 'pharmacie', '+237693953876', '/pathologies/imgteam8.png', 1, 8, datetime('now'), datetime('now'));
